#!/bin/sh

# RUN THIS FROM OUTERMOST DIRECTORY

# cleanup
rm -rf rtl/obj_dir/
rm -f *.vcd

tb/attach_usb.sh

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace rtl/top.sv -Irtl --exe tb/f1_vbuddy.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file
obj_dir/Vtop

